#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Xrandr setup
bash ~/scripts/mon-switch.sh

# Add fonts
xset +fp /usr/share/fonts/local
xset fp rehash

# Start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Set background on wm start
feh ~/.wallpapers/Cliff-4032x3024.jpeg --bg-fill

# Set xsetroot for dwm status bar
bash ~/scripts/xsetroot

exec dwm

#Old WMs
#exec openbox-session
