#!/bin/perl

use Mail::IMAPClient;

%rc = (
    host => "",
    user => "", # Remember to escape the @ symbol
    pass => "",
    );

my $imap = Mail::IMAPClient->new(
    Server => $rc{host},
    User => $rc{user},
    Password => $rc{pass},
    Port => 993,
    Authmechanism => "PLAIN",
    Ssl => 1,
    ) or die "\n";

foreach my $f ($imap->folders("INBOX")) {
    if ($imap->unseen_count($f)==0) {
        print "\n";
    } else {
        print "",
            #$imap->unseen_count($f),
            "\n";
    }
}
