#!/bin/perl

use Mail::IMAPClient;

%rc = (
    host => "",
    user => "",
    pass => "",
    );

my $imap = Mail::IMAPClient->new(
    Server => $rc{host},
    User => $rc{user},
    Password => $rc{pass}
    ) or die "\n";

foreach my $f ($imap->folders("INBOX")) {
    if ($imap->unseen_count($f)==0) {
        print "\n";
    } else {
        print " ",
            $imap->unseen_count($f),
            "\n";
    }
}
