#!/bin/zsh

repo_name=$1
user_name=$2
test -z $repo_name && echo "Repo name required." 1>&2 && exit 1
test -z $user_name && echo "Username required." 1>&2 && exit 1

curl -u $user_name':'$(echo $(cat /home/cory/.config/git/api-key)) https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"

git init
git remote add origin "git@github.com:$user_name/$repo_name.git"
